#ifndef APP_EVENT_H
#define APP_EVENT_H

//sys event base
#define APP_EVENT_SYS_BASE 0x00000000

//default event
typedef enum
{
	APP_EVENT_DEFAULT_BASE = 0x00000100,
	APP_EVENT_DEFAULT_EXIT,
}APP_EVENT_DEFAULT_t;

//音乐播放事件
typedef enum
{
	APP_EVENT_AUDIO_PLAYER_BASE = 0x00000200,
	APP_EVENT_AUDIO_PLAYER_PLAY,
	APP_EVENT_AUDIO_PLAYER_PAUSE,
	APP_EVENT_AUDIO_PLAYER_RESUME,
	APP_EVENT_AUDIO_PLAYER_STOP,
}APP_EVENT_AUDIO_PLAYER_t;

//WIFI事件
typedef enum
{
	APP_EVENT_WIFI_BASE = 0x00000300,
	
}APP_EVENT_WIFI_t;

//SDCARD事件
typedef enum
{
	APP_EVENT_SDCARD_BASE = 0x00000400,
	
}APP_EVENT_SDCARD_t;

//POWER MANAGE事件
typedef enum
{
	APP_EVENT_POWER_BASE = 0x00000500,
}APP_EVENT_POWER_t;

#endif
