#ifndef __MCU_SERIAL_COMM_H__
#define __MCU_SERIAL_COMM_H__
#include <stdio.h>

typedef enum  
{
	DEVICE_NOTIFY_KEY_START = 0,
		
	//上一首键
	DEVICE_NOTIFY_KEY_K1_TAP,
	DEVICE_NOTIFY_KEY_K1_PUSH,
	DEVICE_NOTIFY_KEY_K1_RELEASE,
	DEVICE_NOTIFY_KEY_K1_LONGPRESSED,

	//对话键（原为收藏键）
	DEVICE_NOTIFY_KEY_K2_TAP,
	DEVICE_NOTIFY_KEY_K2_PUSH,
	DEVICE_NOTIFY_KEY_K2_RELEASE,
	DEVICE_NOTIFY_KEY_K2_LONGPRESSED,

	//国学键
	DEVICE_NOTIFY_KEY_K3_TAP,
	DEVICE_NOTIFY_KEY_K3_PUSH,
	DEVICE_NOTIFY_KEY_K3_RELEASE,
	DEVICE_NOTIFY_KEY_K3_LONGPRESSED,

	//睡眠键
	DEVICE_NOTIFY_KEY_K4_TAP,
	DEVICE_NOTIFY_KEY_K4_PUSH,
	DEVICE_NOTIFY_KEY_K4_RELEASE,
	DEVICE_NOTIFY_KEY_K4_LONGPRESSED,

	//本地键
	DEVICE_NOTIFY_KEY_K5_TAP,
	DEVICE_NOTIFY_KEY_K5_PUSH,
	DEVICE_NOTIFY_KEY_K5_RELEASE,
	DEVICE_NOTIFY_KEY_K5_LONGPRESSED,

	//微聊键
	DEVICE_NOTIFY_KEY_K6_TAP,
	DEVICE_NOTIFY_KEY_K6_PUSH,
	DEVICE_NOTIFY_KEY_K6_RELEASE,
	DEVICE_NOTIFY_KEY_K6_LONGPRESSED,

	//收藏键（原为对话键）
	DEVICE_NOTIFY_KEY_K7_TAP,
	DEVICE_NOTIFY_KEY_K7_PUSH,
	DEVICE_NOTIFY_KEY_K7_RELEASE,
	DEVICE_NOTIFY_KEY_K7_LONGPRESSED,

	//下一首键
	DEVICE_NOTIFY_KEY_K8_TAP,
	DEVICE_NOTIFY_KEY_K8_PUSH,
	DEVICE_NOTIFY_KEY_K8_RELEASE,
	DEVICE_NOTIFY_KEY_K8_LONGPRESSED,

	//暂停/播放键
	DEVICE_NOTIFY_KEY_K9_TAP,
	DEVICE_NOTIFY_KEY_K9_PUSH,
	DEVICE_NOTIFY_KEY_K9_RELEASE,
	DEVICE_NOTIFY_KEY_K9_LONGPRESSED,

	//WIFI键
	DEVICE_NOTIFY_KEY_K10_TAP,
	DEVICE_NOTIFY_KEY_K10_PUSH,
	DEVICE_NOTIFY_KEY_K10_RELEASE,
	DEVICE_NOTIFY_KEY_K10_LONGPRESSED,

	//童锁K1+K8
	DEVICE_NOTIFY_KEY_K11_TAP,
	DEVICE_NOTIFY_KEY_K11_PUSH,
	DEVICE_NOTIFY_KEY_K11_RELEASE,
	DEVICE_NOTIFY_KEY_K11_LONGPRESSED,

	//耳灯键
	DEVICE_NOTIFY_KEY_K12_TAP,
	DEVICE_NOTIFY_KEY_K12_PUSH,
	DEVICE_NOTIFY_KEY_K12_RELEASE,
	DEVICE_NOTIFY_KEY_K12_LONGPRESSED,
	
	DEVICE_NOTIFY_KEY_END,
}DEVICE_NOTIFY_KEY_T;
	
typedef void (* mcu_key_cb)(DEVICE_NOTIFY_KEY_T _key_event);
typedef void (* mcu_battery_cb)(float _battery_vol);

void mcu_serial_comm_create(mcu_key_cb _key_cb, mcu_battery_cb _battery_cb);
void keyboard_lock_init(void);
int keyboard_lock(void);
void keyboard_unlock(void);
int keyboard_lock_status(void);
void mcu_serial_send_led_ctrl(uint8_t _enable_bit, uint8_t _cmd);

#endif


