#ifndef __MCU_SERIAL_COMM_H__
#define __MCU_SERIAL_COMM_H__
#include <stdio.h>

#define KEY_VALUE_PREV 				0xA1
#define KEY_VALUE_PLAY 				0xA2
#define KEY_VALUE_NEXT 				0xA3
#define KEY_VALUE_VOL_DOWN 			0xA4
#define KEY_VALUE_VOL_UP 			0xA5
#define KEY_VALUE_WECHAT_START 		0x06
#define KEY_VALUE_WECHAT_STOP 		0x86
#define KEY_VALUE_CHAT_START 		0x07
#define KEY_VALUE_CHAT_STOP 		0x87
#define KEY_VALUE_WIFI_SET 			0xA9
#define KEY_VALUE_CH2EN 			0xAA
#define KEY_VALUE_EN2CH 			0xAB
#define KEY_VALUE_ESP32_START 		0x0C
#define KEY_VALUE_ESP32_STOP 		0x8C
#define KEY_VALUE_COLLECTION 		0xAD
#define KEY_VALUE_PLAY_COLLECTION 	0xCD
#define KEY_VALUE_PLAY_NEWS			0XCE
#define KEY_VALUE_LOW_POWER 		0x15
#define KEY_VALUE_ROBOT_OFF 		0x16
#define KEY_VALUE_MIC_IN 			0x17
#define KEY_VALUE_MIC_OUT 			0x18

typedef enum
{
	UART_ESP32_STATUS_MODE_WIFI_CONNECTING = 0X00,		//ESP32wifi正在连接（断网）
	UART_ESP32_STATUS_MODE_WIFI_CONNECTED = 0X01,		//ESP32WiFi连接成功
	UART_ESP32_STATUS_MODE_WIFI_SETTING = 0X02,			//ESP32启动配网
	UART_ESP32_STATUS_MODE_MUSIC_PLAYING = 0X03,		//ESP32音乐处于播放状态
	UART_ESP32_STATUS_MODE_MUSIC_STOP = 0X04,			//ESP32音乐处于停止状态
	UART_ESP32_STATUS_MODE_CHATING_STATU = 0X05,		//ESP32可以对机器说话的状态
	UART_ESP32_STATUS_MODE_CHAT_FAILED_STATU = 0X06,	//ESP32语音识别失败
	UART_ESP32_STATUS_MODE_CHAT_SUCCESS_STATU = 0X07,	//ESP32语音识别成功
	UART_ESP32_STATUS_MODE_POWER_SUPPLY_STATU = 0X08,	//ESP32充电状态
	UART_ESP32_STATUS_MODE_NOT_POWER_SUPPLY_STATU = 0X09,//ESP32非充电状态
	UART_ESP32_STATUS_MODE_DEVICE_START_STATU = 0X10,	//ESP32已启动状态
}UART_ESP32_STATUS_MODE_t;

extern int g_mic_flag;

void uart_esp32_status_mode(UART_ESP32_STATUS_MODE_t mode);
void mcu_serial_comm_create(int uart_num, int io_rx, int io_tx);

#endif


