#ifndef __ARRAY_MUSIC_H__
#define __ARRAY_MUSIC_H__
 #include <stdio.h>
#include <string.h>

typedef struct
{
    int audio_len;
    char *audio_data;
    char *audio_name;
} FLASH_MUSIC_DATA_T;

typedef enum
{
    FLASH_MUSIC_HELLO_LITTLE_FRIEND,
    FLASH_MUSIC_I_AM_DABAO,
    FLASH_MUSIC_I_AM_HERE_YOU_SAY,
    FLASH_MUSIC_WHY_DO_U_LOOK_FOR_ME,
    FLASH_MUSIC_BATTERY_LOW,
    FLASH_MUSIC_CHILD_LOCK_HAS_BEEN_CLOSED,
    FLASH_MUSIC_CHILD_LOCK_HAS_BEEN_OPENED,
    FLASH_MUSIC_CHINESE_ENGLISH_TRANSLATE,
    FLASH_MUSIC_CONNECT_NETWORK_BEFORE_USE,
    FLASH_MUSIC_CUI_MIAN_QU,
    FLASH_MUSIC_DEVICE_ACTIVATE_FAIL,
    FLASH_MUSIC_DEVICE_ACTIVATE_OK,
    FLASH_MUSIC_DEVICE_SLEEP,
    FLASH_MUSIC_DYY_ERROR_PLEASE_TRY_AGAIN_LATER,
    FLASH_MUSIC_DYY_NINSHUO_WOZAI,
    FLASH_MUSIC_DYY_VOL_MAX,
    FLASH_MUSIC_DYY_VOL_MIN,
    FLASH_MUSIC_DYY_VOLUME_ALREADY_HIGHEST,
    FLASH_MUSIC_DYY_VOLUME_ALREADY_LOWEST,
    FLASH_MUSIC_DYY_VOLUME_CHANGE_OK,
    FLASH_MUSIC_DYY_VOLUME_DOWN,
    FLASH_MUSIC_DYY_VOLUME_UP,
    FLASH_MUSIC_EN_AND_CH_TRANSLATION,
    FLASH_MUSIC_ENGLISH_CHINESE_TRANSLATE,
    FLASH_MUSIC_EQUIPMENT_UPGRADING,
    FLASH_MUSIC_ER_GE,
    FLASH_MUSIC_EXIT_NETWORK_MODE,
    FLASH_MUSIC_GU_SHI,
    FLASH_MUSIC_GUO_XUE,
    FLASH_MUSIC_HI_WE_MEET_AGAIN,
    FLASH_MUSIC_IM_BACK,
    FLASH_MUSIC_KEY_PRESS,
    FLASH_MUSIC_MESSAGE_ALERT,
    FLASH_MUSIC_MSG_SEND,
    FLASH_MUSIC_MUSIC_NOT_FOUND,
    FLASH_MUSIC_MUSIC_PAUSE,
    FLASH_MUSIC_MUSIC_PLAY,
    FLASH_MUSIC_NETWORK_CONNEC_FAILURE,
    FLASH_MUSIC_NETWORK_CONNEC_SUCCESS,
    FLASH_MUSIC_NETWORK_CONNECT_BEFORE_USE,
    FLASH_MUSIC_NETWORK_CONNECT_CONFIG,
    FLASH_MUSIC_NETWORK_CONNECTING,
    FLASH_MUSIC_NETWORK_DISCONNECTED,
    FLASH_MUSIC_NETWORK_POOR,
    FLASH_MUSIC_NEXT_SONG,
    FLASH_MUSIC_NO_MUSIC,
    FLASH_MUSIC_NO_TF_CARD,
    FLASH_MUSIC_NOT_HEAR_CLEARLY_PLEASE_REPEAT,
    FLASH_MUSIC_OPEN_APP_TO_CONNECT_NETWORK,
    FLASH_MUSIC_PLEASE_CLOSE_THE_CHILD_LOCK_FIRST,
    FLASH_MUSIC_PLEASE_RECONNECT_THE_NETWORK,
    FLASH_MUSIC_POOR_NETWORK_SIGNAL,
    FLASH_MUSIC_POWER_OFF,
    FLASH_MUSIC_POWER_ON_GREETING,
    FLASH_MUSIC_PREV_SONG,
    FLASH_MUSIC_SEND_FAIL,
    FLASH_MUSIC_SEND_SUCCESS,
    FLASH_MUSIC_STUDY_ENGLISH_MODE,
    FLASH_MUSIC_TF_CARD_INSERTED,
    FLASH_MUSIC_TF_CARD_PULL_OUT,
    FLASH_MUSIC_UPDATE_FAIL,
    FLASH_MUSIC_UPGRADE_COMPLETE,
    FLASH_MUSIC_WAIT_FOR_SD_SCAN,
    FLASH_MUSIC_WECHAT_SHORT_AUDIO,
    FLASH_MUSIC_YIN_YUE,
    FLASH_MUSIC_YING_YU,
    FLASH_MUSIC_YUE_QI,
}FLASH_MUSIC_INDEX_T;


char *get_flash_music_data(int index);

char *get_flash_music_name(int index);

char *get_flash_music_name_ex(int index);

int get_flash_music_size(int index);

int get_flash_music_max_subscript();

#endif /*__ARRAY_MUSIC_H__*/
